## MLOps Assignment 1

Q1. Print multiplication table from 1 to 10

In [1]:
#write here and run the cell

# Define the size of the multiplication table
size = 10

# Print the table header
print("   ", end="")
for i in range(1, size + 1):
    print(f"{i:4}", end="")
print()

# Print the table rows
for i in range(1, size + 1):
    print(f"{i:2} ", end="")
    for j in range(1, size + 1):
        print(f"{i * j:4}", end="")
    print()

      1   2   3   4   5   6   7   8   9  10
 1    1   2   3   4   5   6   7   8   9  10
 2    2   4   6   8  10  12  14  16  18  20
 3    3   6   9  12  15  18  21  24  27  30
 4    4   8  12  16  20  24  28  32  36  40
 5    5  10  15  20  25  30  35  40  45  50
 6    6  12  18  24  30  36  42  48  54  60
 7    7  14  21  28  35  42  49  56  63  70
 8    8  16  24  32  40  48  56  64  72  80
 9    9  18  27  36  45  54  63  72  81  90
10   10  20  30  40  50  60  70  80  90 100

Q2. Given two lists, l1 and l2, write a program to create a third list l3 by picking an odd-index element from the list l1 and even index elements from the list l2.

In [23]:
#write here and run the cell

l1 = [0,1,2,3,4,5,6,7,8,9]
l2 = [1,2,3,4,5,6,7,8,9,0]

l3 = []
for i in range(len(l1)):
    if i%2 == 1:
        l3.append(l1[i])
    else:
        l3.append(l2[i])

print(l3)

[1, 1, 3, 3, 5, 5, 7, 7, 9, 9]

Q3. Print a this pattern(*)

    * * * * * * * *
      * * * * * * *
        * * * * * *
          * * * * *
            * * * *
              * * *
                * *
                  *

In [24]:
#write here and run the cell

for i in range(8):
    print(' ' * (2 * i), end='')
    print('* ' * (8 - i))

* * * * * * * *
  * * * * * * *
    * * * * * *
      * * * * *
        * * * *
          * * *
            * *
              *

Q4. Create a function named `exponent(base, exp)` that returns an integer representing the result of raising `base` to the power of `exp`.
`exp` is >0.

base = 5
exponent = 4

5 raises to the power of 4 is: 625
i.e. (5 *5 * 5 *5 = 625)

In [25]:
#write here and run the cell

def exponent(base, exp):
    return base ** exp

print(exponent(5, 4))

625

Q5. Create a file named test.txt and insert the following content into it.

    line1
    line2
    line3
    line4
    line5
    line6
    line7

Write a program which write all content of a given file (test.txt) into a new file by skipping line number 5 (line5)

In [26]:
#write here and run the cell

# Function to create a file with the provided data
def create_file():
    content = """line1
                line2
                line3
                line4
                line5
                line6
                line7
                """
    
    with open("test.txt", 'w') as file:
            file.write(content)
    print("File created")

# Function to carry out the desired operation

def read_skip():

    # Reading the original file

    with open("test.txt", 'r') as file:
        lines = file.readlines()
    print("Input file data -> ")
    for i in lines:
        print(i.strip())
    
    print("Writing files to new file")

    # Creating an output file handler
    out_file = open("new_file.txt", 'w')
    for i in range(len(lines)):

        # Skipping the 5th line
        if i != 4:
             out_file.write(lines[i])
    out_file.close()

    # Reading the new file 
    with open("new_file.txt", 'r') as file:
        lines = file.readlines()
    print("Output file data -> ")
    for i in lines:
        print(i.strip())

create_file()
read_skip()

File created
Input file data ->
line1
line2
line3
line4
line5
line6
line7

Writing files to new file
Output file data ->
line1
line2
line3
line4
line6
line7

Q6. Write a program which receives three names from the user in a single input() function call.

    Input: IIT JODHPUR RAJASTHAN

    Output:
    IIT
    JODHPUR
    RAJASTHAN

In [27]:
#write here and run the cell

#input given was "IIT JODHPUR RAJASTHAN"

data = input().split()

for i in data:
    print(i)

IIT
JODHPUR
RAJASTHAN

Q7. Write a program to define a function called show_employee() with the following requirements:

*   It should take the employee's name and salary as input and display both.
*   If the salary is not provided in the function call, assign a default value of 9000 to it.

After passing:

showEmployee("Bill Gates", 12000)

showEmployee("Elon Musk")

It should print:

Name: Bill Gates salary: 12000

Name: Elon Musk salary: 9000

In [28]:
#write here and run the cell

def show_employee(name, salary = 9000):
    print(f"Name : {name} salary : {salary}")

show_employee("Bill Gates", 12000)

show_employee("Elon Musk")

Name : Bill Gates salary : 12000
Name : Elon Musk salary : 9000

Q8. Write a program to identify words that contain both letters and digits from a given input string.

    Given str1 = "Harry25 is Gryffindor Wizard50 and cursed"

    Output:
    Harry25
    Wizard50

In [6]:
#write here and run the cell

import re

def detect_letters_digits(input_string):
    # Define a regex pattern to match words containing both letters and digits
    pattern = re.compile(r'(?:\d+[a-zA-Z]+|[a-zA-Z]+\d+)')
    
    # Find all matches in the input string
    matches = pattern.findall(input_string)
    
    # Print each matched word
    for match in matches:
        print(match)

# Given input string
str1 = "Harry25 is Gryffindor Wizard50 and cursed"

# Find and print words containing both letters and digits
print("Output:")
detect_letters_digits(str1)

Output:
Harry25
Wizard50

Q9. Write a program to substitute each special character in the given string with the symbol #.

    Given: str1 = '/*Modi is @Politician & Melony!!'

    Output: ##Modi is #Politician # Melony##

In [7]:
#write here and run the cell
import re

str1 = '/*Modi is @Politician & Melony!!'

new_string = re.sub('[^a-zA-Z0-9 \n\.]', '#', str1)
print("Output: "+new_string)

Output: ##Modi is #Politician # Melony##

Q10. Construct a Python set that displays elements from both lists as pairs.

    Given:

    first_list = [2, 3, 4, 5, 6, 7, 8]
    second_list = [4, 9, 16, 25, 36, 49, 64]
    Output: Result is  {(6, 36), (8, 64), (4, 16), (5, 25), (3, 9), (7, 49), (2, 4)}

In [31]:
#write here and run the cell
import math

# Define the given lists
first_list = [2, 3, 4, 5, 6, 7, 8]
second_list = [4, 9, 16, 25, 36, 49, 64]

# Create a set to store the pairs
result_set = set()

# Populate the set with pairs
for n1 in first_list:
    for n2 in second_list:
        if n2 == n1 ** 2:  # Check if num2 is the square of num1
            result_set.add((n1, n2))

# Print the result
print("Result is", result_set)

Result is {(7, 49), (2, 4), (4, 16), (8, 64), (6, 36), (3, 9), (5, 25)}

Q11. Define two set A and B consisting of 5 elements. Now print the element after performing


      1.   A-B
      2.   B-A
      3.   A∩B
      4.   A∪B

In [32]:
#write here and run the cell

A = {1, 2, 3, 4, 5, 6, 7, 8, 9, 0}
B = {4, 8, 0, 23, 1, 23, 43, 55, 56}

print("A - B:", A - B)
print("B - A:", B - A)
print("A ∩ B:", A & B)
print("A ∪ B:", A | B)

A - B: {2, 3, 5, 6, 7, 9}
B - A: {56, 43, 55, 23}
A ∩ B: {0, 1, 4, 8}
A ∪ B: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 43, 55, 23, 56}

## Object Oriented Programming Exercise 1:

[Classes and Objects in Python](https://pynative.com/python-classes-and-objects/)

[Instance variables in Python](https://pynative.com/python-instance-variables/)

Q12. Create a Vehicle class with max_speed and mileage instance attributes.

In [12]:
#write here and run the cell

class Vehicle:
    def __init__(self, max_speed, mileage):
        # Initialize the instance attributes
        self.max_speed = max_speed
        self.mileage = mileage
    def print_all(self):
        print("Max Speed: " + str(self.max_speed))
        print("Milage: " + str(self.mileage))

my_vehi = Vehicle(10, 10)
my_vehi.print_all()

Max Speed: 10
Milage: 10

Q13. Create a child class Bus that will inherit all of the variables and methods of the Vehicle class.

Create a Bus object that will inherit all of the variables and methods of the parent Vehicle class and display it.

In [11]:
#write here and run the cell
class Bus(Vehicle):
    def __init__(self, max_speed, mileage, capacity):
        # Initialize the parent class
        super().__init__(max_speed, mileage)
        # Add additional attribute specific to Bus
        self.capacity = capacity

    def print_all(self):
        super().print_all()
        print("Capacity: " + str(self.capacity))

my_bus = Bus(max_speed=80, mileage=50000, capacity=50)
my_bus.print_all()

Max Speed: 80
Milage: 50000
Capacity: 50

### Class Inheritance

Q14. Create a Bus class that inherits from the Vehicle class. Give the capacity argument of Bus.seating_capacity() a default value of 50.

Use the following code for your parent Vehicle class.

    class Vehicle:
      def __init__(self, name, max_speed, mileage):
          self.name = name
          self.max_speed = max_speed
          self.mileage = mileage

      def seating_capacity(self, capacity):
          return f"The seating capacity of a {self.name} is {capacity} passengers"

Expected Output:

    The seating capacity of a bus is 50 passengers

In [13]:
#write here and run the cell
class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers"
    
class Bus(Vehicle):
    def seating_capacity(self, capacity=50):
        return super().seating_capacity(capacity)
    
my_bus = Bus(name="bus", max_speed=80, mileage=50000)
my_bus.seating_capacity()

'The seating capacity of a bus is 50 passengers'

Q15. Create a Bus subclass that inherits from the Vehicle class. By default, the fare for any vehicle is calculated as the seating capacity multiplied by 100. For instances of the Bus class, an additional 10% maintenance fee should be applied to the total fare. Therefore, the final fare for a bus instance will be the sum of the total fare plus an additional 10% of that total fare.

Note: The bus has a seating capacity of 50, so the final fare amount should be 5500. You need to override the fare() method from the Vehicle class in the Bus class.

Use the provided code for the parent Vehicle class. You should access the parent class within a method of the child class.

    class Vehicle:
      def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

      def fare(self):
        return self.capacity * 100

    class Bus(Vehicle):
        pass
        School_bus = Bus("School Volvo", 12, 50)
        print("Total Bus fare is:", School_bus.fare())

    Expected Output:

    Total Bus fare is: 5500.0

In [14]:
#write here and run the cell

class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

    def fare(self):
        return self.capacity * 100

class Bus(Vehicle):
    def fare(self):
        # Calculate the base fare using the parent class method
        base_fare = super().fare()
        # Calculate the total fare including the 10% maintenance fee
        total_fare = base_fare + (0.10 * base_fare)
        return total_fare


# Create an instance of Bus
School_bus = Bus("School Volvo", 12, 50)

# Print the total fare
print("Total Bus fare is:", School_bus.fare())

Total Bus fare is: 5500.0

### Python JSON Exercise
Refer: [Python JSON tutorials](https://pynative.com/python/json/)

Q16. Convert the following dictionary into JSON format

    data = {"key1" : "value1", "key2" : "value2"}
    data = {"key1" : "value1", "key2" : "value2"}

In [15]:
#write here and run the cell

import json

# Given dictionary
data = {"key1": "value1", "key2": "value2"}

# Convert dictionary to JSON format
json_data = json.dumps(data, indent=4)

# Print the JSON data
print(json_data)

{
    "key1": "value1",
    "key2": "value2"
}

Q17. Sort JSON keys in and write them into a file

    sampleJson = {"id" : 1, "name" : "value2", "age" : 29}

    {
          "age": 29,
          "id": 1,
          "name": "value2"
    }

In [16]:
#write here and run the cell

import json

# Given dictionary
sampleJson = {"id": 1, "name": "value2", "age": 29}

# Convert dictionary to JSON format with sorted keys
json_data = json.dumps(sampleJson, sort_keys=True, indent=4)

# Specify the filename
filename = 'sorted_data.json'

# Write the JSON data to a file
with open(filename, 'w') as file:
    file.write(json_data)

print(f"JSON data has been written to {filename}")

JSON data has been written to sorted_data.json